treewide: add missing vmalloc.h include (v6.10 preparation)
Linux commit [1] dropped vmalloc.h from a system header, which causes
this driver to fail compilation:

    .../drivers/trusty/trusty-sched-share.c:112:39: error: call to undeclared function 'vzalloc'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      112 |         sched_share_state->sched_shared_vm = vzalloc(sched_share_state->buf_size);
          |                                              ^

Add the missing implicit include.

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=690da22dbfa8 [1]
      ("asm-generic/io.h: kill vmalloc.h dependency")
Test: compiles
Bug: 354917677
Change-Id: I25a9b428027d42a19b256a198ffb739c563b1404
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from commit d91a449ed01845faf4965b1eb9ccd3115327d5d2)
Signed-off-by: Will McVicker <willmcvicker@google.com>